//DOM - Document Object Model
//Front End Development
//HTML (structure)
//CSS (style)
//JS (logic)

console.log("Hello");
window.console.log("Hello2"); 
console.log(window); //Global Object(generated by Browser)

//When a web page is loaded, the browser creates Document Object Model (DOM) of the page
console.log(window.document); //Just print
console.dir(window.document); //dom properties/methods -- for printing objects
console.log(document.body);

//Console
document.body.style.background = "green";
// document.body.childNodes[3].innerText = "abcd";
//Dom is basically if you want to access your html in js

//DOM Manipulation
//1. Selecting with id
let heading = document.getElementById("heading-id");
// console.log(heading);
console.dir(heading);

//2. Selecting with class
let para = document.getElementsByClassName("para-class");
// console.log(para);
console.dir(para);

//3. Selecting with tag
let par = document.getElementsByTagName("p");
console.dir(par);

//4. Query Selector
// document.querySelector("myId / myClass / tag")
//returns first element
let firstElement = document.querySelector("#heading-id");
console.dir("firstElement: ", firstElement);
console.log("firstElement: ", firstElement);

// document.querySelectorAll("myId / myClass / tag")
//returns a NodeList
let allElement = document.querySelectorAll(".para-class");
console.dir("allElement: ", allElement);


//console
console.dir(document.querySelector("div"));
console.dir(document.querySelector("div").children);
console.dir(document.querySelectorAll("div"));

//Properties (get/set)
/*
• tagName: returns tag for element nodes
• innerText: returns the text content of the element and all its children
• innerHTML : returns the plain text or HTML contents in the element
• textContent: returns textual content even for hidden elements
*/


//Attributes
/*
getAttribute(attr) //to get the attribute value
setAttribute(attr, value) //to set the attribute value
*/

let divAccess = document.querySelector("div");
console.log(divAccess);

let id = divAccess.getAttribute("id");
console.log(id);

//Style
//node.style

/*
Isert Element
• node.append(el) //adds at the end of node (inside)
• node-prepend(el) //adds at the start of node (inside)
• node.before(el) //adds before the node (outside)
• node.after(el) //adds after the node (outside)
Delete Element
• node.remove() //removes the node
*/